services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: hardik8195/jobportal
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database-springecommercewebapp.cjw06mk2y8gd.eu-north-1.rds.amazonaws.com:3306/jobportal
      SPRING_DATASOURCE_USERNAME: hardik
      SPRING_DATASOURCE_PASSWORD: Hard9636
    # Ensure the application service can access the RDS instance
    networks:
      - mynetwork

# Optional: You can define a network for better isolation and management
networks:
  mynetwork:
    driver: bridge
